using FluentMigrator;

namespace Infrastructure.Database.Migrations;

[Migration(3, description: "Create vehicles table")]
public class Vehicles : Migration
{
    public override void Up()
    {
        Execute.Sql("""
                    CREATE TABLE vehicles (
                        vehicle_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        driver_id   BIGINT NOT NULL REFERENCES drivers(driver_id) ON DELETE CASCADE,
                        segment     vehicle_segment NOT NULL,
                        plate       VARCHAR(20) NOT NULL UNIQUE,
                        model       VARCHAR(100) NOT NULL,
                        capacity    INT NOT NULL CHECK (capacity > 0),
                        created_at  TIMESTAMP NOT NULL DEFAULT now()
                    );
                    """);
    }

    public override void Down()
    {
        Execute.Sql("""
                    DROP TABLE IF EXISTS vehicles CASCADE;
                    """);
    }
}
